### ISSUE TITLE
Ensure Image Stays within Container During Zooming

### ISSUE THREAD

**Issue by belwalshubham** [Glazzes/react-native-zoom-toolkit#16]
https://github.com/Glazzes/react-native-zoom-toolkit/assets/61574835/e0dd7381-f34a-4b7d-8d0d-de3b18568d3f

### Summary

I'm encountering an issue where the height of the image increases when zooming using the react-native-zoom-toolkit library. However, the expected behavior is to maintain a fixed height for the image within its container, even when zooming in.

### Issue

When I zoom in on the image, the text below the image overlaps with it. but, expected behavior would be,  image should stay within its container even after zooming, without overlapping the below text.

https://github.com/Glazzes/react-native-zoom-toolkit/assets/61574835/a09fe539-158d-4cb1-863e-67de1f3d9554

### Steps to Reproduce

1. Import the ResumableZoom component from react-native-zoom-toolkit.
2. Wrap an Image component with ResumableZoom.
3. Attempt to zoom in on the image.

**Comment by Glazzes** [comment]
Making a random guess from what I see, I'd try out the following:
```jsx
<View style={{flex: 1, justifyContent:  "center", alignItems: "center", overflow:  "hidden"}}>
  <ResumableZoom>
    <SomeImageHere />
  </ResumableZoom>
</View>
<Text>Random text here</Text>
```

If this doesn't work fix your issue https://snack.expo.dev/, please provide a snack with layout you're building pls

**Comment by belwalshubham** [comment]
Hi @Glazzes the issue fixed now, thanks a lot for your response also 
 image can be made static in the frame? currently I can reduce the image in the frame and can also move minimized image in the frame

**Comment by Glazzes** [comment]
@belwalshubham If you want the image to not be scaled below one, set `scaleMode` property to `ScaleMode.CLAMP`, and if you do not want the image to be dragged you can disable the pan gesture setting `panEnabled` to `false`.

**Comment by belwalshubham** [comment]
@Glazzes When I zoom out the image, it continues to shift from its original position within the container despite its size remaining unchanged. How can I resolve this issue?

**Comment by Glazzes** [comment]
@belwalshubham It's difficult to tell without a video showcasing this issue, provide the proper footage and please make sure it's a smooth video.

**Comment by belwalshubham** [comment]
@Glazzes In the video provided, when zooming out the image using two fingers on a mobile device, it's observed that the image can be easily dragged up and down, resulting in white empty space being displayed. However, this behavior is not desired. The expected behavior is that the image should remain fixed within its container and not be draggable to any position.


Uploading 954a54f6-7f63-46c9-8aea-69d675d8dd01.mp4…

**Comment by belwalshubham** [comment]
@Glazzes If you're unable to view the video above, please refer to the issue at the top where I shared the initial video.

**Comment by Glazzes** [comment]
@belwalshubham At the moment dragging up and down it's an intentional behaviour because of the nature of the algorithmin I've crafted, as far as I know you can drag with both fingers only if `panWithPinch` property is set to `true`, disabling it will probably fix it.

**Comment by belwalshubham** [comment]
Thanks @Glazzes  this works!
also can you help me on the below issue , if you have any idea ?

Here is my ZoombleImage Component
```
import React from 'react';
import { Image, Dimensions } from 'react-native';
import {
  ResumableZoom,
  ScaleMode,
  getAspectRatioSize,
  useImageResolution,
} from 'react-native-zoom-toolkit';
import { COLORS } from '../constants';

type ZoomableImageProps = {
  source: { uri: string };
  imageProps: any;
};

function ZoomableImage({ source, imageProps }: ZoomableImageProps) {
  const { isFetching, resolution } = useImageResolution({ uri: source.uri });

  if (isFetching || !resolution) {
    return null;
  }

  const imageSize = getAspectRatioSize({
    aspectRatio: resolution.width / resolution.height,
    backgroundColor: COLORS.crayolaGrayColor,
    height: Dimensions.get('window').height - Dimensions.get('window').height * 0.3,
    objectFit: 'cover',
  });

  return (
    <ResumableZoom scaleMode={ScaleMode.CLAMP} panWithPinch={false}>
      <Image source={source} style={imageSize} resizeMethod="scale" {...imageProps} />
    </ResumableZoom>
  );
}

export default ZoomableImage;

```

and here is my screen

```
 <ScrollView>
        <View style={styles.container}>
          {isImageLoading && (
            <CenteredLoader isAnimating description="मंडी नीलामी पर्ची का फोटो लोड हो रही है।" />
          )}
          <ZoomableImage
            source={{ uri }}
            imageProps={{
              onLoadStart: () => setIsImageLoading(true),
              onLoadEnd: () => setIsImageLoading(false),
            }}
          />
        </View>
      </ScrollView>
      
      ```
      
Fix Loader Visibility Issue in ZoomableImage Component:
Currently, there is an issue with the visibility of the loader in the ZoomableImage component. When the image loads late due to a low network, the loader does not appear on the screen, leaving the user unaware of the loading process. This impacts the user experience negatively. how can I fix this ?

**Comment by Glazzes** [comment]
Glad to know it worked!
