### ISSUE TITLE
[Bug]: Error: maxWidth and maxHeight parameters are undefined, provide at least one of them when image is square

### ISSUE THREAD

**Issue by efstathiosntonas** [Glazzes/react-native-zoom-toolkit#21]
### Summary

Hi, thank you for creating this module. 

I'm encountering this error when the image is a square eg. 1280x1280:

```
Error: maxWidth and maxHeight parameters are undefined, provide at least one of them
```

When I change the height: 

https://github.com/Glazzes/react-native-zoom-toolkit/blob/2d34962f1f741243a4b6797d2fe834854e218a8d/src/commons/utils/getCropRotatedSize.ts#L23-L27

to:
`aspectRatio >= 1 ? maxHeight : undefined`

The image loads fine and I get this warning: 

```
CropZoom inferred a max crop height of 329.14285714285717, but received a crop height of 386, your cropSize property's height has been clamped to 329.14285714285717
```

I tried it with this image:

<details>
  <summary>Click me</summary>
  
![7515495b-982d-44d2-9931-5a8bbbf27532](https://github.com/Glazzes/react-native-zoom-toolkit/assets/717975/8e798de8-6bf0-49ce-a771-7068cfbd97bd)

</details>

I'm not doing something fancy, just followed the common [/example ](https://github.com/Glazzes/react-native-zoom-toolkit/blob/main/example/src/cropzoom/common-example/CropManagedExample.tsx)

ps. I'm also not rotating or trying to rotate the image.

### Environment

rn 0.74.1

**Comment by efstathiosntonas** [comment]
hi Glazzes, yes, after the small fix everything is fine. Thanks for the update.

/offtopic: 
It seems that sometimes the image won’t load or if it loads I get a weird blurred image instead. It seems like it’s one render behind, the moment I make a small change and fast refresh kicks in, the image shows up. (I’m using the cropper). Also on android, if I don’t set image height/ width among flex:1 the image quality is degraded by a lot.

**Comment by Glazzes** [comment]
I saw the same problems with the image in the issue, sadly that's something I've no control over, I tried the image and it was rendered properly using `{width: '100%', height: '100%'}`, also remember image scaling behaviour on Android depends on what RN thinks is best, so set Image's `resizeMethod` property to `scale`.

Give it a try and let me know.

**Comment by Glazzes** [comment]
Just released version 1.2.2, give it a try!

**Comment by efstathiosntonas** [comment]
@Glazzes just installed 1.2.2, I applied`resizeMethod='scale'` and Android seems fine, now it started on iOS. 

See how the image (same image as above) looks like: 

<details>
  <summary>Click me</summary>

```tsx
        <CropZoom
          OverlayComponent={renderOverlay}
          cropSize={{ width: cropSize, height: 390 }}
          ref={ref}
          resolution={resolution}
          scaleMode={ScaleMode.BOUNCE}
        >
          <Image resizeMethod="scale" source={{ uri: imageUri }} style={styles.image} />
        </CropZoom>
       

style:   image: {
    flex: 1,
    width: "100%",
    height: "100%"
  },
```

![Screenshot 2024-05-29 at 08 13 42](https://github.com/Glazzes/react-native-zoom-toolkit/assets/717975/bf077c33-ac88-4567-ad59-d085d8a75e3e)

</details>

I get the crash again on Android only in a different area this time, same image as the issue, same snippet as above: 

<details>
  <summary>Click me</summary>

![Screenshot 2024-05-29 at 08 17 43](https://github.com/Glazzes/react-native-zoom-toolkit/assets/717975/e1d5dd85-d7dd-4075-8b8a-40377f0213a5)


</details>

**Comment by Glazzes** [comment]
Could you hand me the exact same number you're working with for the `cropSize` variable? Btw, remove `flex: 1` from styles, it's either flex or width and height, not both.

**Comment by efstathiosntonas** [comment]
@Glazzes here are the components: 

`ImageCropper`

```tsx
import React, { useCallback, useEffect, useLayoutEffect, useRef, useState } from "react";
import { Image, View } from "react-native";

import { useIsFocused } from "@react-navigation/native";
import { Action, FlipType, manipulateAsync } from "expo-image-manipulator";
import { OnboardingScreensProps } from "navigation/types";
import { useTranslation } from "react-i18next";
import { createStyleSheet, UnistylesRuntime, useStyles } from "react-native-unistyles";
import {
  CropZoom,
  CropZoomType,
  ScaleMode,
  useImageResolution
} from "react-native-zoom-toolkit";

import { CustomHeader } from "@components/BaseTexts";
import Button from "@components/Buttons/Button";
import { CloseButtonHeader } from "@components/NavigationBars/NavigationBar/components";

import CropOverlay from "@flows/camera/screens/CropImage/CropOverlay";

import { ms } from "@utils/size-matters";
import { dimensions, isIOS } from "@utils/utils";

const cropSize = ms(dimensions.width * 0.8);

const ImageCropper = ({ route, navigation }: OnboardingScreensProps<"ImageCropper">) => {
  const { data, onAddMedia } = route.params;
  const { styles, theme } = useStyles(stylesheet);
  const { t } = useTranslation(["profile_tab", "common"]);

  const ref = useRef<CropZoomType>(null);
  const [result, setResult] = useState<string | undefined>(undefined);

  const imageUri = data.uri;

  const isFocused = useIsFocused();

  const { resolution } = useImageResolution({ uri: imageUri });

  useEffect(() => {
    if (isFocused) {
      UnistylesRuntime.navigationBar.setColor("#000000");
      UnistylesRuntime.statusBar.setColor("#000000");
    }
    return () => {
      UnistylesRuntime.navigationBar.setColor(theme.colors.neutrals["0"]);
      UnistylesRuntime.statusBar.setColor(theme.colors.neutrals["0"]);
    };
  }, [isFocused, theme.colors.neutrals]);

  const renderOverlay = useCallback(() => {
    return <CropOverlay />;
  }, []);

  const done = useCallback(
    (image: any) => {
       onAddMedia(image);
      navigation.goBack();
    },
    [navigation, onAddMedia]
  );

  useLayoutEffect(() => {
    navigation.setOptions({
      headerLeft: () => (
        <CloseButtonHeader
          accessibilityHint={t("crop_image_screen.accessibility.buttons.close.hint")}
          accessibilityLabel={t("crop_image_screen.accessibility.buttons.close.label")}
          isCropImage
          onPress={() => navigation.goBack()}
        />
      )
    });
  }, [navigation, styles.doneText, t, theme.white]);

  const setCrop = useCallback(() => {
    if (ref.current === null) {
      return;
    }
    const cropResult = ref.current.crop(200);

    const actions: Action[] = [];
    if (cropResult.resize !== undefined) {
      actions.push({ resize: cropResult.resize });
    }

    if (cropResult.context.flipHorizontal) {
      actions.push({ flip: FlipType.Horizontal });
    }

    if (cropResult.context.flipVertical) {
      actions.push({ flip: FlipType.Vertical });
    }

    if (cropResult.context.rotationAngle !== 0) {
      actions.push({ rotate: cropResult.context.rotationAngle });
    }

    actions.push({ crop: cropResult.crop });

    manipulateAsync(data?.uri?.[0]?.uri ? data.uri[0].uri : data.uri, actions).then(
      (manipulationResult) => {
        done(manipulationResult.uri);
      }
    );
  }, [data.uri, done]);

  if (resolution === undefined) {
    return null;
  }

  return (
    <View style={styles.container}>
      <CustomHeader
        color="#fff"
        hx="h4"
        style={styles.header}
        text={t("crop_image_screen.move_and_zoom_to_reframe")}
        weight="eb"
      />
      <View style={styles.innerContainer}>
        <CropZoom
          OverlayComponent={renderOverlay}
          cropSize={{ width: cropSize, height: 390 }}
          ref={ref}
          resolution={resolution}
          scaleMode={ScaleMode.BOUNCE}
        >
          <Image source={{ uri: imageUri }} style={styles.image} />
        </CropZoom>
      </View>
      <Button
        hint="test"
        onPress={setCrop}
        size="m"
        style={styles.button}
        title="Add photo"
        type="secondary"
      />
    </View>
  );
};

const stylesheet = createStyleSheet((theme, runtime) => ({
  container: {
    flex: 1,
    backgroundColor: "#000000"
  },
  header: {
    marginHorizontal: theme.spacing.s16,
    marginTop: theme.spacing.mvs24,
    zIndex: 9999
  },
  innerContainer: {
    marginHorizontal: theme.spacing.s16,
    marginTop: theme.spacing.mvs24,
    flex: 1
  },
  cropButtonWrapper: {
    bottom: isIOS ? runtime.insets.bottom + theme.spacing.mvs4 : theme.spacing.mvs24,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    left: 0,
    marginTop: theme.spacing.mvs4,
    position: "absolute",
    right: 0
  },
  cropViewContainer: {
    paddingBottom: theme.spacing.mvs14,
    borderRadius: theme.spacing.mvs20,
    borderColor: "#D9D9D9",
    borderWidth: theme.spacing.s2,
    height: theme.spacing.mvs370
  },
  doneText: {
    color: theme.white,
    ...theme.typography.paragraph.large.semibold
  },
  image: {
    width: "100%",
    height: "100%"
  },
  button: {
    alignSelf: "stretch",
    marginBottom: runtime.insets.bottom,
    marginHorizontal: theme.spacing.s16,
    zIndex: 99999
  }
}));

export default ImageCropper;
```

`CropOverlay`

```tsx
import React from "react";

import Svg, { Defs, Mask, Rect } from "react-native-svg";

import { dimensions } from "@utils/utils";

const { width, height } = dimensions;

const CropOverlay: React.FC = () => {
  const overlayWidth = width * 0.8;
  const overlayHeight = 390;
  const overlayX = (width - overlayWidth) / 2;
  const overlayY = (height - overlayHeight) / 2;
  const borderRadius = 20;

  return (
    <Svg height={height} width={width}>
      <Defs>
        <Mask height={height} id="mask" width={width} x="0" y="0">
          <Rect fill="white" height={height} width={width} x={0} y={0} />
          <Rect
            fill="black"
            height={overlayHeight}
            rx={borderRadius}
            ry={borderRadius}
            width={overlayWidth}
            x={overlayX}
            y={overlayY}
          />
        </Mask>
      </Defs>
      <Rect
        fill="rgba(0, 0, 0, 0.8)" // Overlay color and opacity
        height={height}
        mask="url(#mask)"
        width={width}
        x={0}
        y={0}
      />
      <Rect
        fill="none"
        height={overlayHeight}
        rx={borderRadius}
        ry={borderRadius}
        stroke="#9D9A98"
        strokeWidth={4}
        width={overlayWidth}
        x={overlayX}
        y={overlayY}
      />
    </Svg>
  );
};

export default CropOverlay;
```



ps. I think it would be nice to add the rectangle SVG too among the circle one in the example, not everyone wants to bloat the app with 6MB by using Skia 😅

**Comment by efstathiosntonas** [comment]
It turns out that the moment I set the width to `cropSize={{ width: 390, height: 390 }}` the blur went away.  Seems like a calculation issue, the `ms(width * 0.8)` produces `315.6666666666667` and something goes off. 

What I tried:
1. Hardcoding 315.666 -> blurred image
3. Math.floor(315.666) -> blurred image
4. Made width the same as the height -> 390 -> all good
5. Made width 400, height on 390 -> blurred image

**Comment by Glazzes** [comment]
@efstathiosntonas  Hi there, just to give you an update, dealing with square content has proven to be more annonying than I expected, it may take a few days for me to figure out the math to make the square content fit properly in crop sizes which aspect ratio is not one, I was working on it yesterday and it did work as I expected but it broke the cropper entirely, so yeah pretty much that for the moment.

Bare with me.

**Comment by efstathiosntonas** [comment]
no worries, keep it up! These maths are hard as f 😄

**Comment by Glazzes** [comment]
@efstathiosntonas Hi there, just to give you an update on how this thing is going, last days have the wrost of my life in terms of mental health so you'll have to wait for a little longer.

Sizing right now is working really good, better than before, however the cropper is still fully broken when using the `fixedWidth` argument, pretty much this is how they look now for all three different aspect ratios, while using at the same time the three different aspect ratios on the imgaes, one per each ratio.

| Square | Portrait | Landscape |
|------------|------------|------------------|
|<video src="https://github.com/Glazzes/react-native-zoom-toolkit/assets/52082794/d3aca92f-a54b-4fe6-8d2a-48ef8fb9db85" width="100%" controls /> | <video src="https://github.com/Glazzes/react-native-zoom-toolkit/assets/52082794/d95702ae-9618-4d0e-8e66-4ec7b9600884" width="100%" controls /> | <video src="https://github.com/Glazzes/react-native-zoom-toolkit/assets/52082794/1b1c9fa8-0099-4a50-9611-da84aaf3b9e1" width="100%" controls /> |

**Comment by efstathiosntonas** [comment]
thanks for the heads up! 

no worries at all, mental health is above all!

**Comment by Glazzes** [comment]
I just finished the problem with the cropper entirely this time (I hope), the previous implmentation for the cropping of "uneven" aspect ratios has been fully rewritten, just like you saw in the videos in my last comments, the warning is no longer neccesary and in general it comes to a shorter implementation leading to a small size improvement aswell.

Before plubishing I'd like you to give try a it first, in theory you need to go to your project's `node-modules/react-native-zoom-toolkit` folder and replace `lib` and `src` folders with the contents of the tarball below
[lib.tar.gz](https://github.com/user-attachments/files/15594485/lib.tar.gz)

Let me how it goes!

**Comment by efstathiosntonas** [comment]
@Glazzes thank you for all your effort in this one. 

It is much better but I still encounter the blurred image issue. The first image from Library loads fine and I'm able to crop. 

When I pick a second image then the image is blurred. When I tap save button to crop it throws this error: 

```
﻿﻿Error: Invalid crop options has been passed. Please make sure the requested crop rectangle is inside source image
```

(^^ previously it was saving the image)


I copied the `src/lib` to `/react-native-zoom-toolkit`, killed metro and runned it again with `--reset-cache`.

**Comment by Glazzes** [comment]
That's really an odd behaviour, could you please hand me the exact same numbers you're using for the cropszie property? I just tested with a 2000x2000 picture and it was cropped fine.

**Comment by efstathiosntonas** [comment]
@Glazzes been using these 2 images on iOS Simulator 17.5 and rn 0.74.2, reanimated@3.12.0, rngh@2.16.2:

[images.zip](https://github.com/user-attachments/files/15665902/images.zip)

gist with the code I use: https://gist.github.com/efstathiosntonas/7727b8e84f221a534446e51249bd269b

**Comment by efstathiosntonas** [comment]
I switched to expo-image and the blur is gone. That's really weird, do you think rn Image cache might be causing this?

**Comment by Glazzes** [comment]
@efstathiosntonas Whatever I tell you may be a lie as I'm not sure why it happens, all I know is that RN has a lot non sense stuff I will never be able to comprehend, one just has to flow with them against one's desires, I'm happy the blur went it away nonetheless.

In terms of the crash I made a few adjustments to the lib, everything seems fine here [lib.tar.gz](https://github.com/user-attachments/files/15672360/lib.tar.gz) , the order was fixed to be the one in the docs again https://glazzes.github.io/react-native-zoom-toolkit/guides/cropzoomexpo.html#crop-method, sorry for the inconvenient, give it a try.

**Comment by efstathiosntonas** [comment]
will test it in a while and update.

Have you tried using a fixed with in the cropResult? ie: 

` const cropResult = ref.current.crop(2000)`

**Comment by Glazzes** [comment]
> will test it in a while and update.
> 
> Have you tried using a fixedWidth in the cropResult? ie:
> 
> ` const cropResult = ref.current.crop(2000)`

Yes, with and without the `fixedWidth` parameter.

**Comment by efstathiosntonas** [comment]
@Glazzes everything works as a charm. Thank you for your effort on this one, it was really tricky 😅

**Comment by Glazzes** [comment]
@efstathiosntonas It's good to know it works, even the simplest ideas can turn into tricky and insufferable thoughts when some level of Math is involved in particular for a self taught like myself, however your issue has been quite fun to work with, I would have not thought of changing the way the image renders without looking at what you're attempting to create, so for that all I can say is thanks.

I think the new version may be published by the end of this day, with this outcome I consider this issue to be closed for good now.

**Comment by efstathiosntonas** [comment]
I avoid this kind of math like the plague, my mental health is above all hahaha! Glad I could help to make this library even better, even without touching the code 🤪

**Comment by efstathiosntonas** [comment]
I think you should add extensive comments in the code, I tried to dive into the code but after seeing the complexity I quietly backed up

**Comment by Glazzes** [comment]
Yeah, that's something to work on the near future, however it may be a difficukt to get right as I've been forced to apply a lot of tricks to achieve simple things which are difficult to achieve by a simple usage of GH, for instance: When you're pinching using any of the components offered by this library, what's really being pinched is not even being animated and its always one step behind of what you do.
