### ISSUE TITLE
[Question]: How to use a different animation when swiping in the gallery

### ISSUE THREAD

**Issue by daviddamilola** [Glazzes/react-native-zoom-toolkit#25]
### Summary

Thank you for this amazing library.

Is it possible to use a different animation when swiping between images in the Gallery component? If not, is it possible to remove it all together?

**Comment by Glazzes** [comment]
Hi and thank you 👋!

At the moment that's the only animation supported and can not be changed, however there are plans to support a basic "no animation" mode (a slider) as well as vertical mode.

**Comment by Glazzes** [comment]
Just release version `2.0.1`, slider mode is now the default and you can build your own scroll animation if you have the knowledge to do so.
