### ISSUE TITLE
Gallery Image list bug on android when set intitial index different then 0 example 1,2 or more

### ISSUE THREAD

**Issue by vorn-dev-ni** [Glazzes/react-native-zoom-toolkit#44]
https://github.com/user-attachments/assets/d3096424-29c8-45c9-9d34-d873910869d1

**Comment by Glazzes** [comment]
Hi there, yeah in fact it is a bug. It's caused by some strange reason in which Reanimated's shared values are not assigned properly when inside an `onLayout` event, I'm actually working on it.

**Comment by vorn-dev-ni** [comment]
Yes sir, hopefully u can find it

**Comment by vorn-dev-ni** [comment]
This issue is in the next released yet sir?

**Comment by Glazzes** [comment]
This issue is now fixed in release [2.1.3](https://github.com/Glazzes/react-native-zoom-toolkit/releases/tag/v2.1.3)
