### ISSUE TITLE
[Gallery] Prop support to disable image to zoom at particular index

### ISSUE THREAD

**Issue by cw-nikhilnaik** [Glazzes/react-native-zoom-toolkit#45]
Hi, hope you are having a great day

Lets say I have a gallery component which render's 10 images. But I dont want all 10 images to be zoomed. I dont want the 5th image in array be zoomed. I want the starting 4 images be zoomed and the last 5 images be zoomed not the middle one. 

Is this possible with current version? If we have to add a support for it, then how much effort would that take?

Thankyou

**Comment by Glazzes** [comment]
Hi there, hope you are doing good aswell. It depends on how problematic you find the current way of achieving it is, if you're using the `maxScale` property by providing the resolutions array all you need to do is to set the position 5th with something like `{width: 1, height: 1}` this will keep the maxScale always at 1, in theory its not disabled as you can pinch a bit as long as you hold the gesture, but it's the closest to what you want.

**Comment by cw-nikhilnaik** [comment]
I used the approach you suggested, it works for doubleTap, for unfortunately it was able to be zoomed In and zoomedout. I was able to provide certain changes to your package. If you think this feature will be useful, I will raise a PR or else I will use the feature in my fork.

**Comment by Glazzes** [comment]
Your use case per se is way too niche for a prop to be something this specific, however I'm not against the idea of disabling zoom, maybe `pinchEnabled` and `doubleTap` properties would be good additions, this in combination with the `onIndexchange` callback would suffice your needs.

**Comment by Glazzes** [comment]
I just released version 3.0.0 which includes zoomEnabled and scaleMode properties, both properties when used together may be solve your issues.
