### ISSUE TITLE
[Bug]: getAspectRatioSize.default is not a function 

### ISSUE THREAD

**Issue by Conrador** [Glazzes/react-native-zoom-toolkit#47]
### Summary

After fresh installation and use of CropZoom in my expo app I am instantly receiving such errors on iOS, Is this something connected to usage inside monorepo?: 

![Simulator Screenshot - iPhone 15 Pro - 2024-08-12 at 11 24 12](https://github.com/user-attachments/assets/a2673964-2248-4ebd-b6be-df4d753b34e4)
![Simulator Screenshot - iPhone 15 Pro - 2024-08-12 at 11 23 53](https://github.com/user-attachments/assets/af215c05-1360-4c92-88c6-6bb703fb5b80)

### Environment

expo: 51.0.17
react-native: 0.74.1
react-native-reanimated: 3.14.0
react-native-gesture-handler: 2.16.2
react-native-zoom-toolkit: 2.1.2

Note: I am using monorepo. 

### Steps to Reproduce

1. Install react-native-zoom-toolkit in monorepo package.json 
2. Use CropZoom inside expo project inside monorepo

**Comment by Glazzes** [comment]
Hi there, by looking at the error logs it looks like Reanimated is uncapable to workletize an `export default function`, at the moment I do not have much time to work in this particular issue as it has been described, however I have compiled a version of the library with what I think would fix the issue [lib.tar.gz](https://github.com/user-attachments/files/16603532/lib.tar.gz), to test it go to this library location in the `node_modules` folder and delete all of its contents and replace them by the ones in the tarball, let me if it works.

**Comment by Conrador** [comment]
Yeah, it works!

**Comment by Glazzes** [comment]
As dumb as it sounds, bu yes, it seems to be the solution to this problem. getAspectRatioSize was the only function in the entire codebase that was not an arrow function.

**Comment by Glazzes** [comment]
You can install version 2.1.4 of the library which contains the bug fix.
