### ISSUE TITLE
[Feature]: ResumableZoom support for listening double tap events in onGestureEnd callback

### ISSUE THREAD

**Issue by cheolhow** [Glazzes/react-native-zoom-toolkit#50]
### Summary

`onTap` event also didn't know that the double tap event occurred. 
Only the `onGestureActive` event can listen for double tap events.

### Environment

Expo
iOS Simulator

**Comment by Glazzes** [comment]
Documentation for this property reads as follows **"Callback triggered when a pan gesture or a pinch gesture ends"**, however I will take this issue as an enhacement proposal.

**Comment by Glazzes** [comment]
This is feature has now been added to version 3.0.0
