### ISSUE TITLE
Using Gallery , Image is not displaying  i see pitch black on IOS device

### ISSUE THREAD

**Issue by vorn-tovtrip** [Glazzes/react-native-zoom-toolkit#56]
### Summary

Latest version on android working fine but when i switch to device IOS, image is not showing

### Environment

IOS

**Comment by Glazzes** [comment]
Hi there, the way you redacted your issue made me think images were not displaying in the gallery, I tested it in iOS but images were rendering fine for me.

If you're seeing the image as a pitch black rectangle where the image should be that's actually a React Native issue and it does happen on Android as well, what causes such issue is unclear to me.

Sorry but there's nothing I can do about it as it's not related to this library.
