### ISSUE TITLE
[Question]: Suppress Double Tap Zoom

### ISSUE THREAD

**Issue by josh-platik** [Glazzes/react-native-zoom-toolkit#58]
### Summary

For the Resumable Zoom Component is there a way for me to enable single taps but disable the double tap zoom functionality? 

https://glazzes.github.io/react-native-zoom-toolkit/components/resumablezoom.html#tapsenabled

Thanks for this software, it is fantastic

**Comment by Glazzes** [comment]
Hi there, at the moment there's no way to disable only one of them, however `ResumableZoom` received an update not long ago where it can detect touches via onPress events, you could try something like this:

```tsx
<ResumableZoom tapsEnabled={false}>
  <Pressable onPress={() => console.log("press event")}>
    <Image source={{uri}} style={{width: 200, height: 200}} />
  </Pressable>
</ResumableZoom>
```

There's a downside to consider with this solution, the touch events are strictly bounded to component within it, therefore things like [extendGestures property](https://glazzes.github.io/react-native-zoom-toolkit/components/resumablezoom.html#extendgestures) set to true, at least for touch events would have no effect at all, pinch and pan will keep working fine.
