### ISSUE TITLE
[Question]: How to test gesture events in my component?

### ISSUE THREAD

**Issue by lucianomlima** [Glazzes/react-native-zoom-toolkit#61]
### Summary

First, thanks for this library!

I'm using ResumableZoom inside a photo gallery with a zoom feature with a pinch gesture. I want to test, for example, a callback function passed to onUpdate.

From what I saw in the [Gesture Handler documentation](https://docs.swmansion.com/react-native-gesture-handler/docs/guides/testing
), it's necessary to pass a [testID to find a gesture](https://docs.swmansion.com/react-native-gesture-handler/docs/guides/testing#getbygesturetestidtestid).

ResumableZoom doesn't have a [testID prop](https://github.com/Glazzes/react-native-zoom-toolkit/blob/29ec986a3f4d3532c5cf1ee2d2aa0f90640242a8/src/components/resumable/types.ts#L19-L34) or even refer to the [withTestID](https://github.com/software-mansion/react-native-gesture-handler/blob/0e544e4fee91519d7751c36a40ca0d4dc744be94/src/__tests__/Events.test.tsx#L252-L266) prop in the code, which is necessary to find the gesture.

How can I test a specific event like onUpdate in my app tests? My test is something like to:
```ts
it('should call onUpdate callback when pinch gesture event is fired', () => {
  const resolution = {
    height: 400,
    width: 640,
  };

  mockUseImageResolution.mockReturnValueOnce({
    resolution,
    isFetching: false,
  });

  setup({ item: { id: 'some-photo', uri: 'http://some-photo.jpg' } });

  fireGestureHandler<PinchGesture>(getByGestureTestId('pinch'), []);

  expect(defaultProps.onUpdate).toHaveBeenCalledTimes(1);
});
```

**Comment by Glazzes** [comment]
I'd crave to give you a proper answer, but the reality is that I gave up on testing gestures and rage deleted everything related to them.

The tools provided by Gesture Handler are too primitive to write anything than basic tests, there are things that are 100% untestable like onSwipe callbacks (custom swipe based on pan gesture), gesture config changes and more, I've thinking of writing those basic tests again, but I do not really know if it's even worth it.

At this point in time the only way to test is your hands, sorry.

**Comment by Glazzes** [comment]
@lucianomlima Today I released a new version, it does include testIds for each gesture, GH is still limited in terms of testing and the recommended version to test with is 2.20.0

**Comment by lucianomlima** [comment]
Nice! I'll check out, thanks!
