### ISSUE TITLE
[Question]: How to use this library on a FlatList?

### ISSUE THREAD

**Issue by spicy-xili** [Glazzes/react-native-zoom-toolkit#63]
### Summary

Hello,

I read in the documentation that SnapbackZoom will not bypass zIndex. Do you have an example of how to implement a FlatList with pinchable images? I'm going crazy because I just can't seem to get it to work. Every solution I try feels extremely buggy due to the nature of FlatList, which pre-renders items and overrides zIndexes.

Thanks in advance!

**Comment by Glazzes** [comment]
Hi there, the video footage in SnapbackZoom's documentation is taken from the example app found in this repo and it's in fact a Flatlist.

Talking of Flatlist is important to note that Flatlist does not override zIndex, zIndex is a property that works relative to elements at the same level of nesting as known as sibling elements. What happens in reality is that your components are rendered within an intermediate view provided by the Flatlist, then by the sibling nature of zIndex it gets nullified:
```jsx
// What you want to render
<SnapbackZoom>
  <Image />
</SnapbackZoom>

// What is actually rendered
<View>
  <SnapbackZoom>
    <Image />
  </SnapbackZoom>
</View>
```

Flatlist has a property called `CellRendererComponent` in which you can override this intermediate view and apply your custom zIndex value.

Do not pay too much attention to the example as a whole, but this [file](https://github.com/Glazzes/react-native-zoom-toolkit/blob/main/example/src/snapback/list/MessageList.tsx)
