### ISSUE TITLE
[Bug]: Horizontal panning not working

### ISSUE THREAD

**Issue by MaRaSu** [Glazzes/react-native-zoom-toolkit#71]
### Summary

With ResumableZoom and example code from the module docs I can pinch zoom and pan vertically, but horizontal panning is not working: it either does not pan at all (example code) or with my own images and testing different props I could get some horizontal panning, but not really working properly and also I got sometimes weird effects where Image started to flip between centered image and horizontally panned image (have videos of those if needed).

Happy to help in debugging to identify the root cause of the problem.

### Environment

Expo SDK 51, expo router v3
react-native-gesture-handler 2.16.2.
react-native-reanimated 3.10.1
react-native-zoom-toolkit 3.1.0

Expo dev build, dev-mode, tested on iPhone 14 with iOS 17.6.1

### Steps to Reproduce

1. Copy-paste ResumableZoom example from module documentation as-is, put it into a file which is defined as a Stack.Screen for Expo Router v3
2. Navigate to said screen and try to pinch zoom and pan the image

**Comment by Glazzes** [comment]
Your issue sounds quite strange to me, please share me the videos you've taken.

**Comment by Glazzes** [comment]
@MaRaSu Nice catch, I just fucked up the example in the docs real bad. I forgot if you have the `{flex: 1, justifyContent: "center", alignItem: "center"}` in the parent component it becomes unmesurable... So you just need to remove justifyContent and alignItems from the View enclosing ResumableZoom.

**Comment by MaRaSu** [comment]
@Glazzes thanks for quick replies! Removing those style props was an instant fix, now zooming works very nicely indeed.
