### ISSUE TITLE
[Bug]: Galley is not working with RN 0.76

### ISSUE THREAD

**Issue by jutein** [Glazzes/react-native-zoom-toolkit#76]
### Summary

I've upgraded React native to 0.76, and my gallery isn't working anymore. The image is displayed, but no zoom, scroll, swipe... Seems like gesture handler are not detected

I've tried with basic implementation (just displaying url), no changes

### Environment

react-native: 0.76
react-native-reanimated: 3.16.1
react-native-gesture-handler: 2.21.2

### Steps to Reproduce

Create a screen that display basic gallery:

```
const renderItem = useCallback((item: string) => {
    return (
      <View>
        <Text>{item}</Text>
      </View>
    );
  }, []);
  const keyExtractor = useCallback((item: string, index: number) => {
    return `${item}-${index}`;
  }, []);

  const images = [
    'https://kutyaknak.hu/shop_ordered/73803/pic/gsp.jpg',
    'https://cdn.britannica.com/02/132502-050-F4667944/macaw.jpg',
    'https://assets-global.website-files.com/63634f4a7b868a399577cf37/64665685a870fadf4bb171c2_labrador%20americano.jpg',
    'https://i0.wp.com/bcc-newspack.s3.amazonaws.com/uploads/2023/05/052323-Foxes-in-Millennium-Park-Colin-Boyle-9124.jpg?fit=1650%2C1099&ssl=1',
  ];
  const transition = useCallback(stackTransition, []);

  return (
    <View style={{ flex: 1 }}>
      <Gallery
        data={images}
        keyExtractor={keyExtractor}
        renderItem={renderItem}
        initialIndex={0}
        customTransition={transition}
      />
    </View>
  );
```

Open the app, 1st url is displayed, no interaction possible to see other urls

**Comment by Glazzes** [comment]
@jutein Hi there, I have the library pretty much ready to be released, I would like you to test it before it comes out, this to be sure it works as expected, you can test the latest changes by installing the dev branch:
```sh
yarn add https://github.com/Glazzes/react-native-zoom-toolkit#dev
npm install "https://github.com/Glazzes/react-native-zoom-toolkit#dev" --save
```
Let me know how it works for you, if you can test it on both platforms that would be great!

**Comment by jutein** [comment]
Working great, on both ios and android

**Comment by jutein** [comment]
@Glazzes do you know if you're going to release the new version soon?

**Comment by Glazzes** [comment]
@jutein In a couple of hours, approximately.

**Comment by sohail-wayland** [comment]
I'm trying this dev branch and works fine on iOS and RN 0.76. However, doesn't seem to be responding to any input on Android with RN 0.76. Exact same project, exact same setup. I am using the example structure from the docs in my app as well.

**Comment by sohail-wayland** [comment]
Edit: I found the issue. I am wrapping the Gallery inside a Modal. The touch stops responding on Android but continues to work on iOS. If I make the renderItem only render the <Gallery> it works on both iOS and Android. 

Is using a modal not supported on Android? I would think the most popular use case for the Gallery component is to render it within a modal.

**Comment by Glazzes** [comment]
@sohail-wayland Read this [thins]( https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation#usage-with-modals-on-android) on Gesture Handler documentation, in previous versions of the Gallery I wrapped the gallery with that HOC, because of this [issue](https://github.com/software-mansion/react-native-reanimated/issues/6713) I see myself forced to remove it, try something like this:

```jsx
<Modal animationType="slide" presentationStyle="overFullScreen" visible={modalVisible}>
  <GestureHandlerRootView style={{flex: 1}}>
    <Gallery
	 ref={ref}
         data={images}
	 keyExtractor={keyExtractor}
	 renderItem={renderItem}
	 onTap={onTap}
	 tapOnEdgeToItem={false}
	 //customTransition={transition}
     />
  </GestureHandlerRootView>
</Modal>
```

**Comment by sohail-wayland** [comment]
> @sohail-wayland Read this [thing](https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation#usage-with-modals-on-android) on Gesture Handler documentation, in previous versions of the Gallery I wrapped the gallery with that HOC, because of this [issue](https://github.com/software-mansion/react-native-reanimated/issues/6713) I see myself forced to remove it, try something like this:
> 
> ```js
> <Modal animationType="slide" presentationStyle="overFullScreen" visible={modalVisible}>
>   <GestureHandlerRootView style={{flex: 1}}>
>     <Gallery
> 	 ref={ref}
>          data={images}
> 	 keyExtractor={keyExtractor}
> 	 renderItem={renderItem}
> 	 onTap={onTap}
> 	 tapOnEdgeToItem={false}
> 	 //customTransition={transition}
>      />
>   </GestureHandlerRootView>
> </Modal>
> ```

Can confirm this works. Thanks!

**Comment by Glazzes** [comment]
@jutein @sohail-wayland 4.0.0 has been released.
